# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://github.com/rubocop-hq/rubocop/blob/master/manual/configuration.md

AllCops:
  Include:
    - app/config/routes.rb
    - app/controllers/**/*.rb
    - app/models/*.rb
  Exclude:
    - bin/setup
    - bin/update
    - bin/bundle
    - bin/rails
    - bin/rake
    - bin/spring
    - bin/yarn
    - tmp/**/*
    - storage/**/**


Layout/LineLength:
  Enabled: true
  Max: 100

Style/Documentation:
  Enabled: false

Lint/RaiseException:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Layout/EndOfLine:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false

# Si mas adelante se combinan los 2 estilos desactivar este cop.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact